### PR TITLE
Add missing Tests

### PR DESCRIPTION
**Pull request by cocker-cc**

### CODE REVIEW

**Comment by laugmanuel** [comment]
Do you mind also adding Puppet 7 to the test matrix for Gitlab and GitHub pipelines?

**Comment by cocker-cc** [comment]
`pdk update` in [this PR](https://github.com/dm-drogeriemarkt/puppet-agent_certificate/pull/7) adds Puppet 7

**Comment by laugmanuel** [comment]
> `pdk update` in [this PR](https://github.com/dm-drogeriemarkt/puppet-agent_certificate/pull/7) adds Puppet 7

Can you rebase so tests run against new pipeline?

**Comment by laugmanuel** [comment]
This needs one more rebase to contain tests for Puppet 7

**Pull request merged**
